import {
	titles,
	channelName,
	views,
	timeUploaded,
	bg,
	pf,
} from "./import";

const videoProps = [
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
	{
		title: titles[Math.floor(Math.random() * 14)],
		channelName: channelName[Math.floor(Math.random() * 8)],
		views: views[Math.floor(Math.random() * 8)],
		timeUploaded: timeUploaded[Math.floor(Math.random() * 8)],
		thumbnail: bg[Math.floor(Math.random() * 8)],
		profileImage: pf[Math.floor(Math.random() * 8)],
	},
];

export default videoProps;
